version: "3.9"

services:
  nextapp:
    build:
      context: ./next-app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - nodeapp
    network:
      - next-node

  nodeapp:
    build:
      context: ./node-app
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    network:
      - node-postgres
      - next-node

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=prisma
    volumes:
      - pgdata:/var/lib/postgresql/data
    network:
      - node-postgres

network:
  next-node:
  node-postgres:

volumes:
  pgdata:
